### ISSUE TITLE
Example reading a certificate with a Token

### ISSUE THREAD

**Issue by billib0bs** [jariq/Pkcs11Admin#24] opened 2020-04-30 07:29 UTC
Good afternoon. You can show an example of reading certificate information with eToken. To whom it was issued, the certificate validity period.

**Comment by jariq** [comment] 2020-05-01 20:44
Closing as a duplicate of https://github.com/Pkcs11Interop/Pkcs11Interop/issues/154

**Closed as completed by jariq** 2020-05-01 20:44 UTC
